const Data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: '120',
            countInStock: '10',
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: '100',
            countInStock: '20',
            brand: 'adidas',
            rating: 3.5,
            numReview: 10,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: '150',
            countInStock: '0',
            brand: 'Lacoste',
            rating: 2.5,
            numReview: 10,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Peter England Trousers',
            category: 'Trousers',
            image: '/images/p4.jpg',
            price: '180',
            countInStock: '15',
            brand: 'Peter England',
            rating: 5.0,
            numReview: 15,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'Raymonds Trousers',
            category: 'Trousers',
            image: '/images/p5.jpg',
            price: '160',
            countInStock: '12',
            brand: 'Raymonds',
            rating: 4.3,
            numReview: 10,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Lee Cooper Trousers',
            category: 'Trousers',
            image: '/images/p6.jpg',
            price: '190',
            countInStock: '12',
            brand: 'Lee Cooper',
            rating: 3.5,
            numReview: 10,
            description: 'High quality product',
        },
        {
            _id: '7',
            name: 'Mufti Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: '120',
            countInStock: '10',
            brand: 'Mufti',
            rating: 4.5,
            numReview: 15,
            description: 'High quality product',
        },
    ]
}

module.exports = Data;